services:
  db:
    image: postgres:16.3-bookworm
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"

  rabbitmq:
    image: rabbitmq:4.2-rc-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer:
    build:
      dockerfile: Dockerfile_consumer
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    depends_on:
      - rabbitmq
    command: /app/wait-for-it.sh rabbitmq:5432 -- bash -c "python consumer.py"

  service_desk:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
      - consumer
    volumes:
      - .:/service_desk
    ports:
      - "5000:5000"
    command: /service_desk/wait-for-it.sh db:5672 -- bash -c "gunicorn -b 0.0.0.0:5000 server:app --capture-output"
